version: "3"

services:
  phantom-db-dev1:
    image: mysql:5.7
    container_name: phantom-db-container-dev1
    volumes:
      - ../database:/var/lib/mysql
      - ./init-db-script:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'piala_dev'
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: 'password'
    # networks:
    #   - phantom-network

